/**
 * Vercel serverless entry point for CareerPilot AI.
 *
 * This is the root handler Vercel connects to when serving the app.
 * The Vite build (Nitro "vercel" preset) produces the full SSR bundle
 * in .vercel/output/, and this entry delegates to it.
 *
 * Build:   npm run build   → vite build → .vercel/output/
 * Deploy:  vercel --prod
 */
import type { IncomingMessage, ServerResponse } from "node:http";

export default async function handler(req: IncomingMessage, res: ServerResponse) {
  try {
    // Dynamic import — resolved at runtime from the Nitro build output
    // eslint-disable-next-line @typescript-eslint/ban-ts-comment
    // @ts-ignore — .vercel/output is generated by `vite build`
    const mod = await import("./.vercel/output/functions/__server.func/index.mjs");
    const server = mod.default ?? mod;

    if (typeof server === "function") {
      return server(req, res);
    }

    // Nitro may export a fetch-style handler (Request → Response)
    if (server && typeof server.fetch === "function") {
      const host = req.headers.host ?? "localhost";
      const url = `https://${host}${req.url ?? "/"}`;
      const headers = new Headers();
      for (const [key, value] of Object.entries(req.headers)) {
        if (value) headers.set(key, String(value));
      }

      const response: Response = await server.fetch(
        new Request(url, { method: req.method, headers }),
      );

      res.statusCode = response.status;
      response.headers.forEach((value: string, key: string) =>
        res.setHeader(key, value),
      );
      const body = await response.text();
      res.end(body);
      return;
    }

    res.statusCode = 500;
    res.end("Server handler not found");
  } catch (error) {
    console.error("CareerPilot server error:", error);
    res.statusCode = 500;
    res.end("Internal Server Error");
  }
}
