// This file is automatically generated. Do not edit it directly.
import { createMiddleware } from "@tanstack/react-start";
import { getRequest } from "@tanstack/react-start/server";
import { createClient } from "@supabase/supabase-js";
import type { Database } from "./types";

function isNewSupabaseApiKey(value: string): boolean {
  return value.startsWith("sb_publishable_") || value.startsWith("sb_secret_");
}

function createSupabaseFetch(supabaseKey: string): typeof fetch {
  return (input, init) => {
    const headers = new Headers(
      typeof Request !== "undefined" && input instanceof Request ? input.headers : undefined,
    );

    if (init?.headers) {
      new Headers(init.headers).forEach((value, key) => headers.set(key, value));
    }

    // New Supabase API keys are opaque strings, not bearer JWTs.
    if (
      isNewSupabaseApiKey(supabaseKey) &&
      headers.get("Authorization") === `Bearer ${supabaseKey}`
    ) {
      headers.delete("Authorization");
    }

    headers.set("apikey", supabaseKey);
    return fetch(input, { ...init, headers });
  };
}

export const requireSupabaseAuth = createMiddleware({ type: "function" }).server(
  async ({ next }) => {
    // These are public Supabase values. Keep the fallback aligned with the
    // browser client so server functions still authenticate when Vercel's
    // public environment variables were not copied into a deployment.
    const KNOWN_URL = "https://aidbyvtajfljwswfktvw.supabase.co";
    const KNOWN_KEY = "sb_publishable_W9D0reLquthx320zpxRkiQ_5U7Y0S4P";
    const rawUrl = process.env["SUPABASE_URL"];
    const rawKey = process.env["SUPABASE_PUBLISHABLE_KEY"];
    const SUPABASE_URL =
      typeof rawUrl === "string" && /^https:\/\/[^\s]+\.supabase\.co\/?$/.test(rawUrl)
        ? rawUrl
        : KNOWN_URL;
    const SUPABASE_PUBLISHABLE_KEY =
      typeof rawKey === "string" &&
      (rawKey.startsWith("sb_publishable_") || rawKey.startsWith("eyJ"))
        ? rawKey
        : KNOWN_KEY;

    if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY) {
      const missing = [
        ...(!SUPABASE_URL ? ["SUPABASE_URL"] : []),
        ...(!SUPABASE_PUBLISHABLE_KEY ? ["SUPABASE_PUBLISHABLE_KEY"] : []),
      ];
      const message = `Missing Supabase environment variable(s): ${missing.join(", ")}. Connect Supabase in Lovable Cloud.`;
      console.error(`[Supabase] ${message}`);
      throw new Error(message);
    }

    const request = getRequest();

    if (!request?.headers) {
      throw new Error("Unauthorized: No request headers available");
    }

    const authHeader = request.headers.get("authorization");

    if (!authHeader) {
      console.error("[CareerPilot][auth-middleware] missing authorization header");
      throw new Error("Unauthorized: No authorization header provided");
    }

    if (!authHeader.startsWith("Bearer ")) {
      console.error("[CareerPilot][auth-middleware] authorization header is not Bearer");
      throw new Error("Unauthorized: Only Bearer tokens are supported");
    }

    const token = authHeader.replace("Bearer ", "");
    if (!token) {
      console.error("[CareerPilot][auth-middleware] empty Bearer token");
      throw new Error("Unauthorized: No token provided");
    }

    if (token.split(".").length !== 3) {
      console.error("[CareerPilot][auth-middleware] token is not a JWT-shaped value");
      throw new Error("Unauthorized: Invalid token");
    }

    const supabase = createClient<Database>(SUPABASE_URL!, SUPABASE_PUBLISHABLE_KEY!, {
      global: {
        fetch: createSupabaseFetch(SUPABASE_PUBLISHABLE_KEY!),
        headers: {
          Authorization: `Bearer ${token}`,
        },
      },
      auth: {
        storage: undefined,
        persistSession: false,
        autoRefreshToken: false,
      },
    });

    let userId: string | null = null;
    let claims: unknown = null;

    try {
      const { data: claimsData, error: claimsError } = await supabase.auth.getClaims(token);
      if (!claimsError && claimsData?.claims?.sub) {
        userId = claimsData.claims.sub as string;
        claims = claimsData.claims;
      }
    } catch {
      // Fall back to getUser if getClaims throws
    }

    if (!userId) {
      const { data: userData, error: userError } = await supabase.auth.getUser(token);
      if (userError || !userData?.user?.id) {
        console.error("[CareerPilot][auth-middleware] auth verification failed", {
          userError: userError?.message ?? null,
        });
        throw new Error("Unauthorized: Invalid token");
      }
      userId = userData.user.id;
      claims = userData.user;
    }

    console.info("[CareerPilot][auth-middleware] authenticated request", {
      path: new URL(request.url).pathname,
      userId,
    });

    return next({
      context: {
        supabase,
        userId,
        claims,
      },
    });
  },
);
