// This file is automatically generated. Do not edit it directly.
import { createMiddleware } from "@tanstack/react-start";
import { supabase } from "./client";

// Must be registered as a global `functionMiddleware` in `src/start.ts`; otherwise
// the browser never attaches the bearer token to serverFn RPCs.
export const attachSupabaseAuth = createMiddleware({ type: "function" }).client(
  async ({ next }) => {
    const { data } = await supabase.auth.getSession();
    let session = data?.session;

    // Auto-refresh token if expired or expiring within 60s
    if (session && session.expires_at && session.expires_at * 1000 < Date.now() + 60000) {
      try {
        const refreshRes = await supabase.auth.refreshSession();
        if (refreshRes.data.session) {
          session = refreshRes.data.session;
        }
      } catch (err) {
        console.warn("[CareerPilot][auth-attacher] refreshSession failed:", err);
      }
    }

    const token = session?.access_token;
    return next({
      headers: token ? { Authorization: `Bearer ${token}` } : {},
    });
  },
);
