// This file is automatically generated. Do not edit it directly.
import { createClient } from "@supabase/supabase-js";
import type { Database } from "./types";

function isNewSupabaseApiKey(value: string): boolean {
  return value.startsWith("sb_publishable_") || value.startsWith("sb_secret_");
}

function createSupabaseFetch(supabaseKey: string): typeof fetch {
  return (input, init) => {
    const headers = new Headers(
      typeof Request !== "undefined" && input instanceof Request ? input.headers : undefined,
    );

    if (init?.headers) {
      new Headers(init.headers).forEach((value, key) => headers.set(key, value));
    }

    // New Supabase API keys are opaque strings, not bearer JWTs.
    if (
      isNewSupabaseApiKey(supabaseKey) &&
      headers.get("Authorization") === `Bearer ${supabaseKey}`
    ) {
      headers.delete("Authorization");
    }

    headers.set("apikey", supabaseKey);
    return fetch(input, { ...init, headers });
  };
}

function createSupabaseClient() {
  // Use import.meta.env for client-side (Vite build-time replacement)
  // Fall back to process.env for SSR.
  // The URL and publishable key are PUBLIC (used in browser JS by design);
  // security is enforced by Supabase Row-Level Security policies.

  // Validate that a value looks like a real Supabase URL / key
  // (guards against corrupted env-var values injected at build time).
  const isValidUrl = (v: unknown): v is string =>
    typeof v === "string" && v.startsWith("https://") && v.includes(".supabase.co");
  const isValidKey = (v: unknown): v is string =>
    typeof v === "string" && v.length > 10 && (v.startsWith("sb_publishable_") || v.startsWith("sb_secret_") || v.startsWith("eyJ"));

  const rawUrl = import.meta.env["VITE_SUPABASE_URL"] || process.env["SUPABASE_URL"];
  const rawKey = import.meta.env["VITE_SUPABASE_PUBLISHABLE_KEY"] || process.env["SUPABASE_PUBLISHABLE_KEY"];

  if (!isValidUrl(rawUrl)) {
    throw new Error("Missing or invalid VITE_SUPABASE_URL environment variable. Set it in your .env or Vercel project settings.");
  }
  if (!isValidKey(rawKey)) {
    throw new Error("Missing or invalid VITE_SUPABASE_PUBLISHABLE_KEY environment variable. Set it in your .env or Vercel project settings.");
  }

  return createClient<Database>(rawUrl, rawKey, {
    global: {
      fetch: createSupabaseFetch(rawKey),
    },
    auth: {
      storage: typeof window !== "undefined" ? localStorage : undefined,
      persistSession: true,
      autoRefreshToken: true,
    },
  });
}

let _supabase: ReturnType<typeof createSupabaseClient> | undefined;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";
export const supabase = new Proxy({} as ReturnType<typeof createSupabaseClient>, {
  get(_, prop, receiver) {
    if (!_supabase) _supabase = createSupabaseClient();
    return Reflect.get(_supabase, prop, receiver);
  },
});
